package domain;
// Generated 28-May-2022 04:22:46 by Hibernate Tools 4.3.1



/**
 * Sach generated by hbm2java
 */
public class Sach  implements java.io.Serializable {


     private int masach;
     private Loaisach loaisach;
     private String tensach;
     private float giasach;
     private byte[] anh;

    public Sach() {
    }

	
    public Sach(int masach, Loaisach loaisach, String tensach, float giasach) {
        this.masach = masach;
        this.loaisach = loaisach;
        this.tensach = tensach;
        this.giasach = giasach;
    }
    public Sach(int masach, Loaisach loaisach, String tensach, float giasach, byte[] anh) {
       this.masach = masach;
       this.loaisach = loaisach;
       this.tensach = tensach;
       this.giasach = giasach;
       this.anh = anh;
    }
   
    public int getMasach() {
        return this.masach;
    }
    
    public void setMasach(int masach) {
        this.masach = masach;
    }
    public Loaisach getLoaisach() {
        return this.loaisach;
    }
    
    public void setLoaisach(Loaisach loaisach) {
        this.loaisach = loaisach;
    }
    public String getTensach() {
        return this.tensach;
    }
    
    public void setTensach(String tensach) {
        this.tensach = tensach;
    }
    public float getGiasach() {
        return this.giasach;
    }
    
    public void setGiasach(float giasach) {
        this.giasach = giasach;
    }
    public byte[] getAnh() {
        return this.anh;
    }
    
    public void setAnh(byte[] anh) {
        this.anh = anh;
    }




}


